In [1]:
import numpy as np

# 4 ways of Dot product

# reshape(-1,1)


The reshape(-1, 1) operation reshapes the array into a 2-dimensional array with a single column.
The -1 value acts as a placeholder for the number of rows, allowing NumPy to automatically calculate it based on the array's size.
It is commonly used to convert a 1-dimensional array into a column vector.

In [7]:
# Create a 1D array
arr = np.arange(6)

# Reshape the array to have one column and as many rows as needed (-1)
reshaped_arr = arr.reshape(-1, 1)
print(reshaped_arr)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


# copy() function

The copy() function in NumPy creates a new copy of the array, which is independent of the original array. Any modifications made to the copied array will not affect the original array, and vice versa.

In [8]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a copy of the array
arr_copy = arr.copy()

# Modify the copied array
arr_copy[0] = 100

# Original array remains unchanged
print(arr)       # Output: [1 2 3 4 5]
print(arr_copy)  # Output: [100 2 3 4 5]

[1 2 3 4 5]
[100   2   3   4   5]


#   view()

The view() function in NumPy returns a new array object with the same data as the original array but with a different shape or data type. Unlike copy(), the view() function does not create a new copy of the data; instead, it creates a view of the original array.

In [9]:
arr = np.array([1, 2, 3, 4, 5])

# Create a view of the array
arr_view = arr.view()

# Modify the view
arr_view[0] = 100

# The original array is also affected
print(arr)      # Output: [100   2   3   4   5]
print(arr_view) # Output: [100   2   3   4   5]

[100   2   3   4   5]
[100   2   3   4   5]


# Broadcasting

Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be combined or operated upon together. When performing element-wise operations between arrays of different shapes, NumPy automatically broadcasts the arrays to compatible shapes before applying the operation.



In [10]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar to the array using broadcasting
result = arr + 10

print(result)

[[11 12 13]
 [14 15 16]]
